### ISSUE TITLE
when encrypt_uploads, verify md5 of .key file and attempt to fix before failing

### ISSUE THREAD

**Issue by mieslep** [datastax/diagnostic-collection#130]
A number of .enc artifacts have been uploaded but have been unable to be decrypted. It appears a common failure is added DOS line endings `\r`. To protect against this a Reuben enhancement is requested to add an md5 checksum of the .key file. 

If encrypted uploads to S3 are enabled, verify that the .key file is as expected. If it is not, attempt to get it to match by stripping `\r` from the file. If it still does match, fail with a clear explanation.

**Comment by michaelsembwever** [comment]
> To protect against this a Reuben enhancement is requested to add an md5 checksum of the .key file.

Everything can be done in the repo.

**Comment by michaelsembwever** [comment]
Being worked on in https://github.com/datastax/diagnostic-collection/pull/139
