### ISSUE TITLE
Missing credentialized "dsetool" and "dse client-tool" commands

### ISSUE THREAD

**Issue by suiterdevin** [datastax/diagnostic-collection#73]
Seems like the tool does not pass the cqlsh credentials needed to activate dsetool in secured clusters. Similarly, the "dse" command has some subcommands that require security credentials. I encountered this after setting "is_dse=true" along with the cqlsh and jmx credentials parameters being set in collector.conf and activating a collection against a cluster using authentication. The "dsetool" calls are all failing with authentication errors complaining about the need for credentials.

**Comment by michaelsembwever** [comment]
It has been expected that such cqlsh credentials are passed into the `dt_opts` option, see [here](https://github.com/datastax/diagnostic-collection/blob/master/ds-collector/collector.conf.in#L158).

Are the dsetool credentials always matching the cqlsh credentials?
Can the dsetool subcommand security credentials be put into `dt_opts` and passed to every `dsetool` invocation?

**Comment by brendancicchi** [comment]
The collector does not issue any `dse` commands and I verified that `dt_opts` works for the diagnostic collection for passing options to dsetool. @suiterdevin Is there anything that needs to be covered here that I am missing?

**Comment by suiterdevin** [comment]
No I don't think so, thanks. I haven't tested this yet but I may have overlooked the dt_opts field. The credentials do match the CQLSH but different dsetool makes use of both nodetool/jmx credentials as well as cqlsh so the dt_opts may need both, using the "-a -b -l -p" set. I've got more clusters to test this on but I'm closing this.
