### ISSUE TITLE
collect-info binary missing

### ISSUE THREAD

**Issue by Purneau** [datastax/diagnostic-collection#97]
The README.md mentions collect-info should be (as binary) present in the download. 
For me (downloading the 2.0.2 zip release) it is not. Is something going wrong here? 

I ran into some other issues as well for which I'll try to create PRs later. Thanks.

**Comment by michaelsembwever** [comment]
The download zip is only the source code. As described in the top-level readme, you need to generate a diagnostic bundle first. Part of that generation process is the multi-arch compilation of the rust code into the collect-info binary.
